todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todoapp.urls", namespace="todo")),
]

todoapp/urls.py
from django.urls import path

from todoapp.views import *

urlpatterns = [
    path("", index, name="index"),
    path("tag/", TagListView.as_view(), name="tag-list"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/update/<int:pk>/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/delete/<int:pk>/", TagDeleteView.as_view(), name="tag-delete"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/update/<int:pk>/", TaskUpdateView.as_view(), name="task-update"),
    path("task/delete/<int:pk>/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/update_status/<int:pk>/", task_status_update, name="task-update-status")
]

app_name = "todo"

todoapp/models.py
from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks")

    class Meta:
        ordering = ["completed", "-datetime"]


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

todoapp/forms.py
from django import forms

from todoapp.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateTimeField(widget=forms.SelectDateWidget)

    class Meta:
        model = Task
        fields = ("content", "deadline", "tags")


class TaskSearchForm(forms.Form):
    content = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by content..."})
    )

todoapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from todoapp.forms import TaskForm, TaskSearchForm
from todoapp.models import Task, Tag


def index(request):
    context = {
        "completed_task": Task.objects.filter(completed=True).count(),
        "uncompleted_task": Task.objects.filter(completed=False).count()
    }
    return render(request, "todoapp/index.html", context)


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 9


class TagCreateView(generic.CreateView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")
    fields = "__all__"


class TagUpdateView(generic.UpdateView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")
    fields = "__all__"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 3
    queryset = Task.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("content", "")

        context["search_task"] = TaskSearchForm(initial={
            "content": name
        })

        return context

    def get_queryset(self):
        name = self.request.GET.get("content")

        if name:
            return self.queryset.filter(
                content__icontains=name
            )

        return self.queryset

class TaskCreateView(generic.CreateView):
    model = Task
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskForm


class TaskUpdateView(generic.UpdateView):
    model = Task
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskForm


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


def task_status_update(request, pk):
    task = Task.objects.get(id=pk)
    task.completed = not task.completed
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Todo</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            {% include "includes/sidebar.html" %}
          {% endblock %}
        </div>
        <div class="col-sm-10">
          {% block content %}

          {% endblock %}
        </div>
    </div>
</div>
      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}
</body>
</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}

  <div style="text-align: center">
    {% if page_obj.has_previous %}
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="btn btn-dark">Previous</a>
    {% else %}
        <a href="" class="btn btn-dark">Previous</a>
    {% endif %}
      <span class="btn btn-info">
        {{ page_obj.number }} of {{ paginator.num_pages }}
      </span>
    {% if page_obj.has_next %}
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="btn btn-dark next-page">Next</a>
    {% else %}
        <a href="" class="btn btn-dark next-page">Next</a>
    {% endif %}
  </div>

{% endif %}

templates/includes/sidebar.html
<ul><a href="{% url 'todo:index' %}" class="nav-elem">Home</a></ul>
<ul><a href="{% url 'todo:task-list' %}" class="nav-elem">Tasks</a></ul>
<ul><a href="{% url 'todo:tag-list' %}" class="nav-elem">Tags</a></ul>

templates/todoapp/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Welcome to <strong>TODO</strong> page</h1>
  <h3>Now you have</h3>
  <li>Completed task - {{ completed_task }}</li>
  <li>Uncompleted task - {{ uncompleted_task }}</li>
{% endblock %}

templates/todoapp/tag_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Do you want to delete {{ tag.name }} tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <a href="{% url 'todo:tag-list' %}" class="btn btn-secondary">Cancel</a>
    <input type="submit" value="Confirm" class="btn btn-danger">
  </form>
{% endblock %}

templates/todoapp/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <form action="" method="post">
    <h1>{{ object|yesno:"Update,Create" }} tag</h1>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Confirm" class="btn btn-primary">
  </form>
{% endblock %}

templates/todoapp/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>All tags <a href="{% url 'todo:tag-create' %}" class="btn btn-primary float-right">Create</a></h1>
  {% if tag_list %}
    <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>Title</th>
          </tr>
        </thead>
    {% for tag in tag_list %}
      <tr>
        <th>{{ tag.name }}</th>
        <th><a href="{% url 'todo:tag-update' pk=tag.id%}">update</a></th>
        <th><a href="{% url 'todo:tag-delete' pk=tag.id%}">delete</a></th>
      </tr>
    {% endfor %}
    </table>
  {% else %}
    <p>Now we don't have tags</p>
  {% endif %}
{% endblock %}

templates/todoapp/task_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Do you want to delete {{ task.name }} tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <a href="{% url 'todo:task-list' %}" class="btn btn-secondary">Cancel</a>
    <input type="submit" value="Confirm" class="btn btn-danger">
  </form>
{% endblock %}

templates/todoapp/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="content-details">

    <h1>{{ object|yesno:"Update,Create" }} task</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <input type="submit" value="Confirm" class="btn btn-primary">
    </form>

  </div>
{% endblock %}

templates/todoapp/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Tasks list
    <a href="{% url 'todo:task-create' %}" class="btn btn-primary float-right">Create</a>
  </h1>
  <form action="" method="get" class="form-inline">
   {{ search_task|crispy }}
    <input type="submit" value="search" class="btn btn-warning">
  </form>
  <br>
  {% if task_list %}
    {% for task in task_list %}
      <p>{{ task.content }} -
        {% if task.completed %}
          <strong style="color: green">Done</strong>
          <a href="{% url 'todo:task-update-status' pk=task.id %}" class="btn btn-secondary float-right">Undo</a>
        {% else %}
          <strong style="color: crimson">Not done</strong>
          <a href="{% url 'todo:task-update-status' pk=task.id %}" class="btn btn-success float-right">Complete</a>
        {% endif %}

      </p>
      <p>Created at - {{ task.datetime }}</p>
      <p>
        Tags:
        {% for tag in task.tags.all %}
          {{ tag }}
        {% endfor %}
        <a href="{% url 'todo:task-update' pk=task.id%}" class="btn btn-primary">update</a>
        <a href="{% url 'todo:task-delete' pk=task.id%}" class="btn btn-danger">delete</a>
      </p>
      <hr>
    {% endfor %}

  {% else %}
    <p>Now we don't have tasks</p>
  {% endif %}
{% endblock %}